import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "PasteProject",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main>
					<div className="bg-gradient-to-b from-neutral-700 to-neutral-500 w-full h-[5vh] flex items-center justify-center border-b-2 border-neutral-300">
						<h1 className="font-extrabold text-2xl font-mono">
							Paste-Project
						</h1>
					</div>
					{children}
				</main>
			</body>
		</html>
	);
}
